version: "3"
services:
  client:
    image: "rahulshinde276/client"
    mem_limit: 64m
    hostname: client 
  
  server:
    image: "rahulshinde276/server"
    mem_limit: 64m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT

  worker:
    image: "rahulshinde276/worker"
    mem_limit: 64m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT

  nginx:
    image: "rahulshinde276/nginx"
    mem_limit: 64m
    ports:
      - '80:80'