name: Multi Container Docker Build

on:
  push:
    branches:
      - master

jobs:
  docker-push:
    name: Push Images to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -f ./client/Dockerfile.dev -t rahulshinde276/client-dev ./client
      - run: docker run -e CI=true rahulshinde276/client-dev npm test
      - run: docker build -t rahulshinde276/client ./client
      - run: docker build -t rahulshinde276/worker ./worker
      - run: docker build -t rahulshinde276/nginx ./nginx
      - run: docker build -t rahulshinde276/server ./server
      - run: docker push rahulshinde276/client
      - run: docker push rahulshinde276/worker
      - run: docker push rahulshinde276/nginx
      - run: docker push rahulshinde276/server

  webapp-deploy:
    name: Deploy WebApp to Elastic Beanstalk
    needs: docker-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-container
          environment_name: Multi-container-env
          version_label: 12345
          region: us-west-2
          deployment_package: deploy.zip